### ISSUE TITLE
Zemljevidi

### ISSUE THREAD

**Issue by katykro** [katykro/APPR-2015-16#2]
Spoštovani, mene zanima kako naj na zemljevid označim mesta ter kako naj za moške in ženske prikažem cepljenost (moški bi imeli moder krog, ženske rdečega na zemljevidu - če se to da in če je sploh smiselno). Zanima me tudi, kaj naj naredim pri napredni analizi, ker sem naredila zemljevid, ki vsebuje skupine, vendar imam težavo, ker vsakič znova, ko zaženem program, pomeša skupine med seboj in tako niso pravilno pobarvane.

**Comment by jaanos** [comment]
Če hočeš na zemljevid dodati mesta, potrebuješ njihove zemljepisne koordinate in imena - lahko jih spraviš v datoteko CSV in to uvoziš. Potem lahko točke narišeš z `geom_point`, imena pa z `geom_text` - poglej si zadnji primer v [datoteki z vaj](https://ucilnica.fmf.uni-lj.si/mod/resource/view.php?id=17641) (na voljo je na spletni učilnici).

Kar se tiče stopnje cepljenosti, imaš za nekatere države več podatkov, tako da bo treba izbrati enega (npr. najnovejšega). Za lokacije krogov lahko vzameš kar povprečje vseh točk, ki definirajo državo. Potem lahko narediš nekaj takega:

``` R
cep.zadnja <- cepljenost %>% group_by(Drzava) %>% filter(Leto == max(Leto))
svet.tocke <- svet3 %>% group_by(id, name_long) %>%
  summarise(x = mean(long), y = mean(lat))
cep.tocke <- inner_join(cep.zadnja, svet.tocke, by = c("Drzava" = "name_long"))

ggplot() + geom_polygon(data = svet3, aes(x=long, y=lat, group = group),
                        color = "grey") +
  geom_point(data = cep.tocke, aes(x = x, y = y, size = Cepljenost.Z),
             color = "red")
```

Če bi hotela prikazati na istem zemljevidu podatke za oba spola, bi morala premisliti, kako hočeš podatke prikazati - morda en krog zraven drugega, ali pa en čez drugega. V slednjem primeru bi bilo treba paziti, da je večji krog vedno spodaj - je pa res, da so razlike tako majhne, da se večinoma sploh ne bi opazilo, da imaš dva kroga.

Barve se pri razvrščanju v skupine spreminjajo, ker je `kmeans` naključna metoda, ki ne označi vedno skupin na isti način. Kar lahko narediš, je to, da iz vsake skupine izbereš eno reprezentativno državo (torej tako, za katero veš, da bo v želeni skupini). Ko definiraš spremenljivko `dobro.slabo3`, torej k razpredelnici `skupine3` za indekse vrstic podaj kar imena teh držav, indeks stolpca pa naj bo `"skupina"`, kakor je ime stolpcu v `skupine3`.
