### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by katykro** [katykro/APPR-2015-16#3]
Spoštovani, menim, da sem z izdelavo projekta končala, tako da bi prosila, da mi dodate povezavo na zagovore.
https://github.com/katykro/APPR-2015-16
LP, Katarina Kromar

**Comment by jaanos** [comment]
V redu, bom dodal povezavo na repozitorij za zagovore. S profesorjem se lahko domeniš glede termina zagovora.
